# Generated by Django 5.0.3 on 2024-03-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverlevel',
            name='level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')]),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
        migrations.AlterField(
            model_name='sensoralert',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home'),
        ),
    ]
