# Generated by Django 5.0.3 on 2024-03-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_caregiverlevel_level_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='elderly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.person'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('has_accepted', models.BooleanField(default=False)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caregiver')),
                ('sensor_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensoralert')),
            ],
        ),
    ]
