# Generated by Django 5.0.3 on 2024-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_home_elderly_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoralert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
