# Generated by Django 5.0.3 on 2024-04-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensoralert_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverlevel',
            name='level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='caregiver',
            unique_together={('elderly', 'caregiver')},
        ),
    ]
