# Generated by Django 5.0.3 on 2024-04-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_caregiverlevel_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiverlevel',
            name='wait_time',
            field=models.IntegerField(default=600),
        ),
    ]
