# Generated by Django 5.0.3 on 2024-04-17 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_person_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverlevel',
            name='wait_time',
            field=models.IntegerField(default=600, validators=[django.core.validators.MinValueValidator(20)]),
        ),
    ]
